import type {InferCreateForm, InferEditForm} from "../../../../../core/helpers/schemaDefBuilder";

// ProductOrders are system-generated by the checkout process — they cannot be created or edited
// through the standard CRUD form flow. The SchemaDef is intentionally empty; the route uses
// empty Zod schemas for createSchema/editSchema to satisfy the factory interface.

export const ProductOrderSchemaDef = {} as const;

export type CreateProductOrderFormType = InferCreateForm<typeof ProductOrderSchemaDef>;
export type EditProductOrderFormType = InferEditForm<typeof ProductOrderSchemaDef> & {_id: string};
