import type {InferCreateForm, InferEditForm} from "../../../../../core/helpers/schemaDefBuilder";

// PaymentTransactions are system-generated by the payment processing flow — they cannot be created
// or edited through the standard CRUD form flow. The SchemaDef is intentionally empty.

export const PaymentTransactionSchemaDef = {} as const;

export type CreatePaymentTransactionFormType = InferCreateForm<typeof PaymentTransactionSchemaDef>;
export type EditPaymentTransactionFormType = InferEditForm<typeof PaymentTransactionSchemaDef> & {_id: string};
