import type {InferCreateForm, InferEditForm} from "../../../../../core/helpers/schemaDefBuilder";

// PosOrders are system-generated by the till pay API — they cannot be created or edited
// through the standard CRUD form flow. The SchemaDef is intentionally empty; the route uses
// empty Zod schemas for createSchema/editSchema to satisfy the factory interface.

export const PosOrderSchemaDef = {} as const;

export type CreatePosOrderFormType = InferCreateForm<typeof PosOrderSchemaDef>;
export type EditPosOrderFormType = InferEditForm<typeof PosOrderSchemaDef> & {_id: string};
